# Setup
title:               Miki Vanousek's blog
tagline:             
description:         'You can find my notes here.'
domain:              mikulasvanousek.github.io
baseurl:             /blog
url:                 https://mikulasvanousek.github.io
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Miki Vanoušek
  url:               https://linktr.ee/vanousek
  email:             vanousekmikulas@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Exclude symbolic links
#exclude: [drafts, includes,layouts,posts,site]
